# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/tijsv/Documents/UAsem3/DigitaleElektronica/Opdracht1/project_1/IP/VideoMemory/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tijsv/Documents/UAsem3/DigitaleElektronica/Opdracht1/project_1/IP/VideoMemory/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/tijsv/Documents/UAsem3/DigitaleElektronica/Opdracht1/project_1/IP/VideoMemory/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tijsv/Documents/UAsem3/DigitaleElektronica/Opdracht1/project_1/IP/VideoMemory/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
