# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/Nexys-4-DDR-Master_RandromTriangle.xdc

# IP: D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/ClockingWizard/ClockingWizard.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockingWizard || ORIG_REF_NAME==ClockingWizard} -quiet] -quiet
