# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.cache/wt [current_project]
set_property parent.project_path D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/FPA.coe
read_vhdl -library xil_defaultlib {
  D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_Bresenham/project_Bresenham.srcs/sources_1/new/Bresenham.vhd
  D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.srcs/sources_1/new/LFSR_ext.vhd
  D:/Documenten/UAsem2/DigitaleElektronica/DigitaleElektronica-sem1-2/5-Redscreen/Opdracht_VGA/Opdracht_VGA.srcs/sources_1/new/Pixel_Pulser_H.vhd
  D:/Documenten/UAsem2/DigitaleElektronica/DigitaleElektronica-sem1-2/5-Redscreen/Opdracht_VGA/Opdracht_VGA.srcs/sources_1/new/Pixel_Pulser_V.vhd
  D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.srcs/sources_1/new/driehoek.vhd
  D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.srcs/sources_1/new/TrianglePrep.vhd
  D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/project_RandomDriehoeken.srcs/sources_1/new/project_Driehoeken.vhd
}
read_ip -quiet D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/ClockingWizard/ClockingWizard.xci
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/ClockingWizard/ClockingWizard_board.xdc]
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/ClockingWizard/ClockingWizard.xdc]
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/ClockingWizard/ClockingWizard_ooc.xdc]

read_ip -quiet D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/TriangleFifo/TriangleFifo.xci
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/TriangleFifo/TriangleFifo.xdc]
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/TriangleFifo/TriangleFifo_ooc.xdc]

read_ip -quiet D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/VideoMemory/VideoMemory.xci
set_property used_in_implementation false [get_files -all d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoeken/IP/VideoMemory/VideoMemory_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/Nexys-4-DDR-Master_RandromTriangle.xdc
set_property used_in_implementation false [get_files D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/Nexys-4-DDR-Master_RandromTriangle.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top project_Driehoeken -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef project_Driehoeken.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file project_Driehoeken_utilization_synth.rpt -pb project_Driehoeken_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
