# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo.xci
# IP: The module: 'TriangleFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo.xci
# IP: The module: 'TriangleFifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Documenten/UAsem3/DigitaleElektronica/Digitale_elektronica/project_RandomDriehoek/IP/TriangleFifo/TriangleFifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TriangleFifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
